
## What does TF actually do?
- TF provides primitives for defining funcs on tensors and automatically computing their derivatives(倒数).


## What's a Tensor?

- tensors are multilinear maps from vector spaces【矢量空间、向量空间】 to the real numbers (**V** vector space, and $V^{*}$ dual space【对偶空间、共轭空间、初等泛函】)
  $$ f : V^{*} × ... V^{*} × V × ... V → R $$

- A scalar is a tensor ($ f: R → R,~ f(e_1) = c$)
- A vector is a tensor ($ f: R^n → R,~f(e_i) = v_i$)
- A matrix is a tensor ($ f: R^n × R^m → R,~f(e_i,e_j) = A_{ij}$)
- Common to have fixed basis, **so a tensor can be represented as multidimensional array of numbers**.











## TensorFlow vs. Numpy

- Few people make this comparison, but TensorFlow and Numpy are quite similar. (Both are **N-d** array libraries!)
- Numpy has Ndarray support, but doesn't offer methods to create tensor functions and automatically compute derivatives (+ no GPU support)






## Simple Numpy Recap

In [3]:
import numpy as np
a = np.zeros((2,2))
b = np.ones((2,2))
print(a)
print(b)

np.sum(b, axis=1)




[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]
 [ 1.  1.]]


array([ 2.,  2.])

## Repeat in TensorFlow

In [ ]:
import tensorflow as tf

tf.InteractiveSession()

a = tf.zeros((2,2))
b = tf.ones((2,2))

tf.reduce_sum(b, reduction_indices=1).eval()
array([2., 2.], dtype=float32)

a.get_shape()
TensorShape([Dimension(2), Dimension(2)])

tf.reshape(a, (1,4)).eval()
array([[0., 0., 0., 0.]], dtype=float32)




- TensorFlow computations define a **computation graph** that has no numerical value until evaluated!


